/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubespbogui;

import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hafidz
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    private Kompetisi tmpKomp;
    private database db;
    private Tim tim;
    private Pemain pemain;
    public View() {
        initComponents();
        tmpKomp = new Kompetisi();
        tim=new Tim();
        fillListKompetisi();
        firstLaunch();
        startPane();
    }
    private void firstLaunch(){
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3, false);
        jTabbedPane1.setEnabledAt(4, false);
    }
    private void startPane(){
        bEditKompetisi.setVisible(false);
        bDeleteKompetisi.setVisible(false);
        bPilihKompetisi.setVisible(false);
        bOKEditKompetisi.setVisible(false);
        bOKEditTim.setVisible(false);
        bOKEditPemain.setVisible(false);
        bCancelEditKompetisi.setVisible(false);
        bCancelEditTim.setVisible(false);
        bCancelEditPemain.setVisible(false);
        bAddKompetisi.setVisible(true);
        bAddTim.setVisible(true);
        bAddPemain.setVisible(true);
    }
    private void kompetisiSelected(){
        bEditKompetisi.setVisible(true);
        bDeleteKompetisi.setVisible(true);
        bPilihKompetisi.setVisible(true);
    }
    private void fillListKompetisi(){
        DefaultListModel m = new DefaultListModel();
        String allData = tmpKomp.getListKompetisi();
        String[] dataTuple = allData.split(" \n");
        String[][] data = new String[dataTuple.length][];
        String view;
        for (int i = 0; i < dataTuple.length;i++){
            data[i] = dataTuple[i].split(" ; ");
            view = Arrays.toString(data[i]);
            view = view.replaceAll("[^A-Za-z]+", "");
            m.addElement(view);
        }
        lKompetisi.setModel(m);
    }
    private void fillListTim(){
        DefaultComboBoxModel m1 = new DefaultComboBoxModel();
        DefaultListModel m2 = new DefaultListModel();
        String allData = tim.getListTim(tmpKomp.getNama());
        String[] dataTuple = allData.split(" \n");
        String[][] data = new String[dataTuple.length][];
        String view;
        for (int i = 0; i < dataTuple.length;i++){
            data[i] = dataTuple[i].split(" ; ");
            view = Arrays.toString(data[i]);
            view = view.replaceAll("[^A-Za-z]+", "");
            m1.addElement(view);
            m2.addElement(view);
        }
        cNamaTim.setModel(m1);
        lListTim.setModel(m2);
    }
    private void filltableKlasemen(){
    String allData = tim.getListTimFull(tmpKomp.getNama());
        String[] dataTuple = allData.split(" \n");
        String[][] data = new String[dataTuple.length][];
        for (int i = 0; i < dataTuple.length;i++){
            data[i] = dataTuple[i].split(" ; ");
        }
        String [] title = {"Nama TIM","Win","Lose","Draw","Point"};
        tabKlasemen.setModel(new DefaultTableModel(data,title));
    }
    private void setBukaPendaftaran(boolean a){
        bEdit.setVisible(a);
        bDelete.setVisible(a);
        bAddTim.setVisible(a);
        bAddPemain.setVisible(a);
        tNamaTim.setEditable(a);
        tNamaPEmain.setEditable(a);
        tNoPunggung.setEditable(a);
        jTabbedPane1.setEnabledAt(2, !(a));
        jTabbedPane1.setEnabledAt(3, !(a));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        labelWelcome = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pKompetisi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tNamaKompetisi = new javax.swing.JTextField();
        tMaxTim = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lKompetisi = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDetail = new javax.swing.JTextArea();
        bAddKompetisi = new javax.swing.JButton();
        bEditKompetisi = new javax.swing.JButton();
        bPilihKompetisi = new javax.swing.JButton();
        bDeleteKompetisi = new javax.swing.JButton();
        bOKEditKompetisi = new javax.swing.JButton();
        bCancelEditKompetisi = new javax.swing.JButton();
        pPendaftaran = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tNamaTim = new javax.swing.JTextField();
        bAddTim = new javax.swing.JButton();
        bOKEditTim = new javax.swing.JButton();
        bCancelEditTim = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cNamaTim = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tNamaPEmain = new javax.swing.JTextField();
        tNoPunggung = new javax.swing.JTextField();
        cPosisi = new javax.swing.JComboBox();
        bAddPemain = new javax.swing.JButton();
        bOKEditPemain = new javax.swing.JButton();
        bCancelEditPemain = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lListTim = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabListPemain = new javax.swing.JTable();
        bEdit = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        dummy = new javax.swing.JLabel();
        tbTutupPendaftaran = new javax.swing.JToggleButton();
        pKlasemen = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabKlasemen = new javax.swing.JTable();
        bLihatJadwal = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pJadwalPertandingan = new javax.swing.JPanel();
        bMulaiPertandingan = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tJadwalPertandingan = new javax.swing.JTable();
        pPertandingan = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        labTim1 = new javax.swing.JLabel();
        labTim2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        spinGoal1 = new javax.swing.JSpinner();
        spinGoal2 = new javax.swing.JSpinner();
        bSetButton2 = new javax.swing.JButton();
        bSetButton1 = new javax.swing.JButton();
        bEndPertandingan = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane8.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelWelcome.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        labelWelcome.setText("Welcome to Futsal Application...");

        jLabel1.setText("Nama Kompetisi :");

        jLabel2.setText("Maksimal Tim     :");

        lKompetisi.setBorder(javax.swing.BorderFactory.createTitledBorder("List Kompetisi"));
        lKompetisi.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lKompetisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lKompetisiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lKompetisi);

        taDetail.setColumns(20);
        taDetail.setRows(5);
        taDetail.setBorder(javax.swing.BorderFactory.createTitledBorder("Detil"));
        taDetail.setEnabled(false);
        jScrollPane2.setViewportView(taDetail);

        bAddKompetisi.setText("Add");
        bAddKompetisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddKompetisiActionPerformed(evt);
            }
        });

        bEditKompetisi.setText("Edit");
        bEditKompetisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditKompetisiActionPerformed(evt);
            }
        });

        bPilihKompetisi.setText("Pilih");
        bPilihKompetisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPilihKompetisiActionPerformed(evt);
            }
        });

        bDeleteKompetisi.setText("Delete");
        bDeleteKompetisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteKompetisiActionPerformed(evt);
            }
        });

        bOKEditKompetisi.setText("OK");
        bOKEditKompetisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKEditKompetisiActionPerformed(evt);
            }
        });

        bCancelEditKompetisi.setText("Cancel");
        bCancelEditKompetisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelEditKompetisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pKompetisiLayout = new javax.swing.GroupLayout(pKompetisi);
        pKompetisi.setLayout(pKompetisiLayout);
        pKompetisiLayout.setHorizontalGroup(
            pKompetisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKompetisiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pKompetisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pKompetisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pKompetisiLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tNamaKompetisi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pKompetisiLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tMaxTim, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pKompetisiLayout.createSequentialGroup()
                        .addComponent(bOKEditKompetisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancelEditKompetisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAddKompetisi)))
                .addGap(18, 18, 18)
                .addGroup(pKompetisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pKompetisiLayout.createSequentialGroup()
                        .addComponent(bEditKompetisi)
                        .addGap(18, 18, 18)
                        .addComponent(bPilihKompetisi)
                        .addGap(18, 18, 18)
                        .addComponent(bDeleteKompetisi)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pKompetisiLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        pKompetisiLayout.setVerticalGroup(
            pKompetisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKompetisiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pKompetisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pKompetisiLayout.createSequentialGroup()
                        .addGroup(pKompetisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tNamaKompetisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pKompetisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tMaxTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pKompetisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bAddKompetisi)
                            .addComponent(bCancelEditKompetisi)
                            .addComponent(bOKEditKompetisi))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pKompetisiLayout.createSequentialGroup()
                        .addGroup(pKompetisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pKompetisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bEditKompetisi)
                    .addComponent(bPilihKompetisi)
                    .addComponent(bDeleteKompetisi))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kompetisi", pKompetisi);

        pPendaftaran.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pendaftaran TIm"));

        jLabel3.setText("Nama Tim :");

        bAddTim.setText("Add");
        bAddTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddTimActionPerformed(evt);
            }
        });

        bOKEditTim.setText("OK");
        bOKEditTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKEditTimActionPerformed(evt);
            }
        });

        bCancelEditTim.setText("Cancel");
        bCancelEditTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelEditTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNamaTim))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bOKEditTim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancelEditTim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAddTim)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tNamaTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddTim)
                    .addComponent(bOKEditTim)
                    .addComponent(bCancelEditTim)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pendaftaran Pemain"));

        jLabel4.setText("Nama Tim :");

        cNamaTim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "null" }));

        jLabel5.setText("Nama Pemain :");

        jLabel6.setText("No Punggung :");

        jLabel7.setText("Posisi :");

        cPosisi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Striker", "Gelandang", "Back", "Kiper" }));

        bAddPemain.setText("Add");
        bAddPemain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddPemainActionPerformed(evt);
            }
        });

        bOKEditPemain.setText("OK");

        bCancelEditPemain.setText("Cancel");
        bCancelEditPemain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelEditPemainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cNamaTim, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNamaPEmain))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNoPunggung)
                            .addComponent(cPosisi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(bOKEditPemain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancelEditPemain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAddPemain)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cNamaTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tNamaPEmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tNoPunggung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cPosisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddPemain)
                    .addComponent(bOKEditPemain)
                    .addComponent(bCancelEditPemain)))
        );

        lListTim.setBorder(javax.swing.BorderFactory.createTitledBorder("List Tim"));
        lListTim.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lListTim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lListTimMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lListTim);

        tabListPemain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabListPemain);

        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        dummy.setText("Nama Kompetisinya");

        tbTutupPendaftaran.setText("Tutup Pendaftaran");
        tbTutupPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTutupPendaftaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pPendaftaranLayout = new javax.swing.GroupLayout(pPendaftaran);
        pPendaftaran.setLayout(pPendaftaranLayout);
        pPendaftaranLayout.setHorizontalGroup(
            pPendaftaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPendaftaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPendaftaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pPendaftaranLayout.createSequentialGroup()
                        .addComponent(dummy)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pPendaftaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pPendaftaranLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pPendaftaranLayout.createSequentialGroup()
                        .addComponent(bEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tbTutupPendaftaran)))
                .addContainerGap())
        );
        pPendaftaranLayout.setVerticalGroup(
            pPendaftaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPendaftaranLayout.createSequentialGroup()
                .addGroup(pPendaftaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPendaftaranLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dummy))
                    .addGroup(pPendaftaranLayout.createSequentialGroup()
                        .addGroup(pPendaftaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pPendaftaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bEdit)
                            .addComponent(bDelete)
                            .addComponent(tbTutupPendaftaran))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pendaftaran", pPendaftaran);

        tabKlasemen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tabKlasemen);

        bLihatJadwal.setText("Lihat Jadwal Pertandingan");

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pKlasemenLayout = new javax.swing.GroupLayout(pKlasemen);
        pKlasemen.setLayout(pKlasemenLayout);
        pKlasemenLayout.setHorizontalGroup(
            pKlasemenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKlasemenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pKlasemenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pKlasemenLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bLihatJadwal)))
                .addContainerGap())
        );
        pKlasemenLayout.setVerticalGroup(
            pKlasemenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKlasemenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pKlasemenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLihatJadwal)
                    .addComponent(jButton1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Klasemen", pKlasemen);

        bMulaiPertandingan.setText("Mulai Pertandingan");

        tJadwalPertandingan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tJadwalPertandingan);

        javax.swing.GroupLayout pJadwalPertandinganLayout = new javax.swing.GroupLayout(pJadwalPertandingan);
        pJadwalPertandingan.setLayout(pJadwalPertandinganLayout);
        pJadwalPertandinganLayout.setHorizontalGroup(
            pJadwalPertandinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJadwalPertandinganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pJadwalPertandinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pJadwalPertandinganLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bMulaiPertandingan)))
                .addContainerGap())
        );
        pJadwalPertandinganLayout.setVerticalGroup(
            pJadwalPertandinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJadwalPertandinganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bMulaiPertandingan)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Jadwal Pertandingan", pJadwalPertandingan);

        jLabel8.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        jLabel8.setText("vs");

        labTim1.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        labTim1.setText("TIM 1");

        labTim2.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        labTim2.setText("TIM 2");

        jLabel11.setText("No Punggung Pemain :");

        jLabel12.setText("No Punggung Pemain :");

        bSetButton2.setText("Set Goal");

        bSetButton1.setText("Set Goal");

        bEndPertandingan.setText("Akhiri Pertandingan");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("Live Update Goal"));
        jScrollPane6.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pPertandinganLayout = new javax.swing.GroupLayout(pPertandingan);
        pPertandingan.setLayout(pPertandinganLayout);
        pPertandinganLayout.setHorizontalGroup(
            pPertandinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPertandinganLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(pPertandinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPertandinganLayout.createSequentialGroup()
                        .addGroup(pPertandinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSetButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPertandinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pPertandinganLayout.createSequentialGroup()
                                    .addComponent(labTim1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spinGoal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(79, 79, 79)
                        .addGroup(pPertandinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pPertandinganLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(257, 257, 257))
                            .addGroup(pPertandinganLayout.createSequentialGroup()
                                .addGroup(pPertandinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(pPertandinganLayout.createSequentialGroup()
                                        .addComponent(spinGoal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labTim2))
                                    .addComponent(bSetButton2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(66, 66, 66))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPertandinganLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bEndPertandingan)
                        .addContainerGap())))
        );
        pPertandinganLayout.setVerticalGroup(
            pPertandinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPertandinganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPertandinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTim1)
                    .addComponent(jLabel8)
                    .addComponent(labTim2)
                    .addComponent(spinGoal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinGoal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pPertandinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pPertandinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pPertandinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSetButton2)
                    .addComponent(bSetButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pPertandinganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bEndPertandingan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pertandingan", pPertandingan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelWelcome)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAddKompetisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddKompetisiActionPerformed
        // TODO add your handling code here:
        if(tNamaKompetisi.getText().equals("")||tMaxTim.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informasi yang dimasukkan kurang", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            tmpKomp = new Kompetisi(((String) tNamaKompetisi.getText()),(Integer.valueOf((String) tMaxTim.getText())));
            tmpKomp.saveKompetisi();
            taDetail.append("Data berhasil dimasukan \n");
            String allData = tmpKomp.getListKompetisi();
            String[] dataTuple = allData.split(" \n");
            String[][] data = new String[dataTuple.length][];
            for (int i = 0; i < dataTuple.length;i++){
                data[i] = dataTuple[i].split(" ; ");
                taDetail.append(dataTuple[i]);
            }
            fillListKompetisi();
            tNamaKompetisi.setText("");
            tMaxTim.setText("");
        }
    }//GEN-LAST:event_bAddKompetisiActionPerformed

    private void bEditKompetisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditKompetisiActionPerformed
        // TODO add your handling code here:
        bOKEditKompetisi.setVisible(true);
        bCancelEditKompetisi.setVisible(true);
        bAddKompetisi.setVisible(false);
        tmpKomp.selectKompetisi(lKompetisi.getSelectedValue().toString());
        tNamaKompetisi.setText(""+tmpKomp.getNama());
        tMaxTim.setText(""+tmpKomp.getMaxTim());
    }//GEN-LAST:event_bEditKompetisiActionPerformed

    private void bPilihKompetisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPilihKompetisiActionPerformed
        // TODO add your handling code here:
        tmpKomp.selectKompetisi(lKompetisi.getSelectedValue().toString());
        fillListTim();
        JOptionPane.showMessageDialog(null, "Kompetisi Berhasil terpilih", "Sukses", JOptionPane.WARNING_MESSAGE);
        cNamaTim.addItem(evt);
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setSelectedIndex(1);
        dummy.setText("Kompetisi: "+tmpKomp.getNama());
        startPane();
    }//GEN-LAST:event_bPilihKompetisiActionPerformed

    private void lKompetisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lKompetisiMouseClicked
        // TODO add your handling code here:
        String temp=tmpKomp.getDetilKompetisi(lKompetisi.getSelectedValue().toString());
        taDetail.setText(temp);
        kompetisiSelected();
    }//GEN-LAST:event_lKompetisiMouseClicked

    private void bAddTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddTimActionPerformed
        // TODO add your handling code here:
        tmpKomp.selectKompetisi(lKompetisi.getSelectedValue().toString());
        if(tNamaTim.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informasi yang dimasukkan kurang", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            tim=new Tim(tNamaTim.getText());
            tim.saveTim(tmpKomp.getNama(), tmpKomp.getMaxTim());
            fillListTim();
            tNamaTim.setText("");
        }
    }//GEN-LAST:event_bAddTimActionPerformed

    private void bDeleteKompetisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteKompetisiActionPerformed
        // TODO add your handling code here:
        tmpKomp.selectKompetisi(lKompetisi.getSelectedValue().toString());
        tmpKomp.removeKompetisi();
        fillListKompetisi();
    }//GEN-LAST:event_bDeleteKompetisiActionPerformed

    private void bOKEditKompetisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKEditKompetisiActionPerformed
        // TODO add your handling code here:
        String temp=tmpKomp.getNama();
        tmpKomp.setNama(tNamaKompetisi.getText());
        tmpKomp.setMaxTim(Integer.valueOf(tMaxTim.getText()));
        tmpKomp.updateKompetisi(temp);
        fillListKompetisi();
        startPane();
    }//GEN-LAST:event_bOKEditKompetisiActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        if(tabListPemain.getSelectedRow()>=0){
            //visible button for edit pemain
            bAddPemain.setVisible(false);
            bOKEditPemain.setVisible(true);
            bCancelEditPemain.setVisible(true);
            bAddTim.setVisible(true);
            bOKEditTim.setVisible(false);
            bCancelEditTim.setVisible(false);
        }else if (lListTim.getSelectedValue()!=null){
            //tim.selectTim(lListTim.getSelectedValue().toString());
            //visible button for edit tim
            bAddTim.setVisible(false);
            bOKEditTim.setVisible(true);
            bCancelEditTim.setVisible(true);
            bAddPemain.setVisible(true);
            bOKEditPemain.setVisible(false);
            bCancelEditPemain.setVisible(false);
            tNamaTim.setText(lListTim.getSelectedValue().toString());
        }
    }//GEN-LAST:event_bEditActionPerformed

    private void lListTimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lListTimMouseClicked
        // TODO add your handling code here:
        tabListPemain.clearSelection();
    }//GEN-LAST:event_lListTimMouseClicked

    private void bCancelEditKompetisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelEditKompetisiActionPerformed
        // TODO add your handling code here:
        bOKEditKompetisi.setVisible(false);
        bAddKompetisi.setVisible(true);
        tNamaKompetisi.setText(null);
        tMaxTim.setText(null);
        bCancelEditKompetisi.setVisible(false);
    }//GEN-LAST:event_bCancelEditKompetisiActionPerformed

    private void bOKEditTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKEditTimActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bOKEditTimActionPerformed

    private void bCancelEditTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelEditTimActionPerformed
        // TODO add your handling code here:
        tNamaTim.setText(null);
        startPane();
    }//GEN-LAST:event_bCancelEditTimActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        // TODO add your handling code here:
        if(tabListPemain.getSelectedRow()>=0){
            //deletePemain
        }else if (lListTim.getSelectedValue()!=null){
            //deleteTim
        }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void tbTutupPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTutupPendaftaranActionPerformed
        // TODO add your handling code here:
        startPane();
        filltableKlasemen();
        setBukaPendaftaran(!(tbTutupPendaftaran.isSelected()));
    }//GEN-LAST:event_tbTutupPendaftaranActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        filltableKlasemen();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bAddPemainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddPemainActionPerformed
        // TODO add your handling code here:
        tmpKomp.selectKompetisi(lKompetisi.getSelectedValue().toString());
        String tmp = tmpKomp.getNama();
        if(tNamaPEmain.getText().equals("") && tNoPunggung.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informasi yang dimasukkan kurang", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            pemain=new Pemain(tNamaPEmain.getText(),(Integer.parseInt(tNoPunggung.getText())),cPosisi.getSelectedItem().toString());
            pemain.savePemain(tmp,cNamaTim.getSelectedItem().toString(),tNamaPEmain.getText(),Integer.parseInt(tNoPunggung.getText()),cPosisi.getSelectedItem().toString());
            tNamaPEmain.setText("");
            tNoPunggung.setText("");
        }
    }//GEN-LAST:event_bAddPemainActionPerformed

    private void bCancelEditPemainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelEditPemainActionPerformed
        // TODO add your handling code here:
        tNamaPEmain.setText("");
        tNoPunggung.setText("");
    }//GEN-LAST:event_bCancelEditPemainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddKompetisi;
    private javax.swing.JButton bAddPemain;
    private javax.swing.JButton bAddTim;
    private javax.swing.JButton bCancelEditKompetisi;
    private javax.swing.JButton bCancelEditPemain;
    private javax.swing.JButton bCancelEditTim;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bDeleteKompetisi;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bEditKompetisi;
    private javax.swing.JButton bEndPertandingan;
    private javax.swing.JButton bLihatJadwal;
    private javax.swing.JButton bMulaiPertandingan;
    private javax.swing.JButton bOKEditKompetisi;
    private javax.swing.JButton bOKEditPemain;
    private javax.swing.JButton bOKEditTim;
    private javax.swing.JButton bPilihKompetisi;
    private javax.swing.JButton bSetButton1;
    private javax.swing.JButton bSetButton2;
    private javax.swing.JComboBox cNamaTim;
    private javax.swing.JComboBox cPosisi;
    private javax.swing.JLabel dummy;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JList lKompetisi;
    private javax.swing.JList lListTim;
    private javax.swing.JLabel labTim1;
    private javax.swing.JLabel labTim2;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JPanel pJadwalPertandingan;
    private javax.swing.JPanel pKlasemen;
    private javax.swing.JPanel pKompetisi;
    private javax.swing.JPanel pPendaftaran;
    private javax.swing.JPanel pPertandingan;
    private javax.swing.JSpinner spinGoal1;
    private javax.swing.JSpinner spinGoal2;
    private javax.swing.JTable tJadwalPertandingan;
    private javax.swing.JTextField tMaxTim;
    private javax.swing.JTextField tNamaKompetisi;
    private javax.swing.JTextField tNamaPEmain;
    private javax.swing.JTextField tNamaTim;
    private javax.swing.JTextField tNoPunggung;
    private javax.swing.JTextArea taDetail;
    private javax.swing.JTable tabKlasemen;
    private javax.swing.JTable tabListPemain;
    private javax.swing.JToggleButton tbTutupPendaftaran;
    // End of variables declaration//GEN-END:variables
}
